name: Manual Android Build

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # or your desired Java version
        distribution: 'adopt' # Specify the distribution, e.g., 'adopt', 'adopt-hotspot', etc.

    - name: Cache Gradle distribution
      uses: actions/cache@v2
      with:
        path: /opt/gradle
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Install Gradle
      run: |
        # Install Gradle version
        wget https://services.gradle.org/distributions/gradle-7.2-bin.zip -P /tmp
        unzip -d /opt/gradle /tmp/gradle-7.2-bin.zip
        export GRADLE_HOME=/opt/gradle/gradle-7.2
        export PATH=$GRADLE_HOME/bin:$PATH

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-apks
        path: app/build/outputs/apk/

    - name: Upload APKs to DigitalOcean Spaces
      run: |
        echo "access_key = $DO_SPACES_KEY" >> ~/.s3cfg
        echo "secret_key = $DO_SPACES_SECRET" >> ~/.s3cfg
        s3cmd put app/build/outputs/apk/app-debug.apk s3://origin.nyc3.digitaloceanspaces.com/APKs/app-debug.apk
      env:
        DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
        DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}

# ... (you can add more steps here, such as tests, code quality checks, etc.)
