name: Manual Android Build

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # or your desired Java version
        distribution: 'adopt' # Specify the distribution, e.g., 'adopt', 'adopt-hotspot', etc.

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # Add more steps here for running tests, code quality checks, etc.
